symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 10800 # J'ai mis 3h car je n'arrive pas à régler la date de demande de token (2h avant notre fuseau) donc le token s'expire en réalité 1h après avoir été demandé
    throttle_limit: 300 #5min avant que l'utilisateur puisse redemander un autre token
    enable_garbage_collection: true