vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        products:
            uri_prefix: /video/
            upload_destination: '%kernel.project_dir%/public/video/films'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
