# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        subtitle_files:
            uri_prefix: /subtitle
            upload_destination: '%kernel.project_dir%/public/subtitle'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
