@startuml CineCourts
title "Ajout note"

|#LightBlue|Utilisateur|
|#Orange|Admin|
|#Red|Serveur|

    |Utilisateur|
    start
    :Selectionne un film;
    |Serveur|
    :Reçoit la requete;
    |Utilisateur|
    :Affiche la page du film;
    :Ajoute une note;
    |Serveur|
    :Reçoit la requete;
    :Enregistre la note dans la BDD;
    end