controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

films_par_genre:
    path: /films/genre/{id}
    controller: App\Controller\FilmsController::filmsByGenre
    methods: GET
